# Managed by copier — changes may be overwritten by `copier update`
name: Nix Setup
description: Install Nix and enable magic-nix-cache

inputs:
  nix-extra-conf:
    description: Additional nix.conf settings
    required: false
    default: ""

runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21
      with:
        extra-conf: |
          eval-cores = 1
          ${{ inputs.nix-extra-conf }}
        diagnostic-endpoint: ""
    - uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
      with:
        diagnostic-endpoint: ""
